# Generated by Django 5.2.4 on 2025-07-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('models_used', models.JSONField(default=dict, help_text='Model usage breakdown')),
                ('avg_response_time', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('daily_breakdown', models.JSONField(default=dict, help_text='Daily usage breakdown')),
                ('models_used', models.JSONField(default=dict, help_text='Model usage breakdown')),
                ('avg_response_time', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('daily_limit', 'Daily Limit Warning'), ('monthly_limit', 'Monthly Limit Warning'), ('cost_limit', 'Cost Limit Warning'), ('quota_exceeded', 'Quota Exceeded'), ('api_error', 'API Error')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('chat', 'Chat Completion'), ('completion', 'Text Completion'), ('image', 'Image Generation'), ('embedding', 'Embedding'), ('moderation', 'Content Moderation')], default='chat', max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('prompt_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('completion_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_time', models.DecimalField(decimal_places=3, default=0, help_text='Response time in seconds', max_digits=8)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('openrouter_id', models.CharField(blank=True, max_length=100)),
                ('actual_model', models.CharField(blank=True, help_text='Actual model used by OpenRouter', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
