# Generated by Django 5.2.4 on 2025-07-21 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('usage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyusagesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='marketplace.aimodel'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyusagesummary',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyusagesummary',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['user', 'created_at'], name='usage_usage_user_id_7af0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['model', 'created_at'], name='usage_usage_model_i_86fc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['created_at'], name='usage_usage_created_acba7e_idx'),
        ),
    ]
