// Generated by Copilot
/**
 * Simple utility to estimate token count from text
 * Note: This is a rough approximation. For more accurate counts, 
 * you would typically use a proper tokenizer library like GPT Tokenizer
 */

/**
 * Estimates the number of tokens in the given text
 * A very simple implementation that splits by whitespace
 * In practice, most LLMs use more sophisticated tokenization
 * @param {string} text - The text to count tokens for
 * @returns {number} - Estimated token count
 */
export const estimateTokenCount = (text) => {
  if (!text || text.trim() === '') return 0;
  
  // Split by whitespace as a simple approximation
  // In practice, tokens are more granular and language-specific
  return text.trim().split(/\s+/).length;
};
