# Generated by Django 5.2.4 on 2025-07-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text='OpenRouter model ID', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('chat', 'Chat'), ('completion', 'Completion'), ('image', 'Image Generation'), ('embedding', 'Embedding'), ('moderation', 'Moderation')], default='chat', max_length=20)),
                ('context_length', models.IntegerField(help_text='Maximum context length in tokens')),
                ('max_output_tokens', models.IntegerField(blank=True, null=True)),
                ('prompt_cost', models.DecimalField(decimal_places=6, help_text='Cost per 1M input tokens', max_digits=10)),
                ('completion_cost', models.DecimalField(decimal_places=6, help_text='Cost per 1M output tokens', max_digits=10)),
                ('quality_score', models.DecimalField(decimal_places=1, default=0.0, help_text='Quality score out of 10', max_digits=3)),
                ('speed_score', models.DecimalField(decimal_places=1, default=0.0, help_text='Speed score out of 10', max_digits=3)),
                ('popularity_score', models.DecimalField(decimal_places=1, default=0.0, help_text='Popularity score out of 10', max_digits=3)),
                ('supports_functions', models.BooleanField(default=False)),
                ('supports_vision', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='marketplace.modelprovider')),
            ],
            options={
                'ordering': ['-is_featured', '-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('avg_response_time', models.DecimalField(decimal_places=3, default=0, help_text='Average response time in seconds', max_digits=8)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Success rate percentage', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='marketplace.aimodel')),
            ],
        ),
    ]
